#!/bin/bash

#
# Install terraform
#

if [ ! -x "$(which terraform)" ]; then
  export release=AmazonLinux
  sudo yum install -q -y yum-utils
  sudo yum-config-manager -q -y --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo
  sudo yum -q -y install terraform  

  echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' >~/.terraform.rc
fi


#
# Configure shell
#

export AWS_ACCOUNT=$(aws sts get-caller-identity|jq -r .Account)

alias tf="terraform"
alias tfi="terraform init"
alias tfp="terraform plan -var account=${AWS_ACCOUNT} -input=false -out tfplan"
alias tfa="terraform apply -auto-approve -input=false tfplan"
